; Sala1 is rotated 90 degrees to connect with Sala2 on its right side.
[TileSala1]
xposition=3.313
yposition=-5.206
side=TileSideBedroom1
rotation=90

[TileSala2]
xposition=6.813116
yposition=0.04395962
side=TileSideStudy
